export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #6ee7b7 0%, #34d399 100%)' },   // Soft Green
  { id: 2, bgcolor: 'linear-gradient(135deg, #fde68a 0%, #fcd34d 100%)' },   // Soft Amber
  { id: 3, bgcolor: 'linear-gradient(135deg, #bae6fd 0%, #7dd3fc 100%)' },   // Soft Sky Blue
  { id: 4, bgcolor: 'linear-gradient(135deg, #fca5a5 0%, #f87171 100%)' },   // Soft Red
  { id: 5, bgcolor: 'linear-gradient(135deg, #93c5fd 0%, #60a5fa 100%)' },   // Soft Blue
  { id: 6, bgcolor: 'linear-gradient(135deg, #d1d5db 0%, #9ca3af 100%)' },   // Soft Gray
  { id: 7, bgcolor: 'linear-gradient(135deg, #f9a8d4 0%, #f472b6 100%)' },   // Soft Pink
  { id: 8, bgcolor: 'linear-gradient(135deg, #99f6e4 0%, #5eead4 100%)' },   // Soft Teal
  { id: 9, bgcolor: 'linear-gradient(135deg, #ddd6fe 0%, #c4b5fd 100%)' },   // Soft Purple
  { id: 10, bgcolor: 'linear-gradient(135deg, #fecaca 0%, #fca5a5 100%)' }, // Light Coral Red
];




const APP_FEATURES = [ 
  {
    id: "01",
    title: "Tailored Just For You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas"
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with Al-powered detail"
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description: "Expand personal notes to any question and pin important ones to the top-making your learning more organized"
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description: "Beyond just answers-unlock detailed concept explanations generated by AI, helping you truly master each"
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation"
  }
];
export default APP_FEATURES;